---
- name: Install and configure WordPress
  hosts: wordpress
  become: true
  roles:
    - roles
# Edited by Mohamed Khaled - Testing Git contribution

# Edited by Ahmed Gamal - Testing Git contribution

